### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by Rapsssito** [Rapsssito/react-native-tcp-socket#1]
Hello everyone!
I have created **`react-native-tcp-socket`**, since the original [`react-native-tcp`](https://github.com/PeelTechnologies/react-native-tcp) repository was abandoned long ago. As @phillbaker [commented](https://github.com/PeelTechnologies/react-native-tcp/issues/108#issuecomment-530605215) in the original repository, non active user has maintainer access on that repository, so `react-native-tcp` cannot be moved.

There are some forks still being actively maintained, like @aprock['s one](https://github.com/aprock/react-native-tcp), so I wanted to ask as much `react-native-tcp`'s forks maintainers as possible for help bringing `react-native-tcp` back to life in this repository.

I will post bellow a list with the maintainers I could find. **If you are willing to help, reply to this issue please. Everyone is welcome!**

* @phillbaker 
* @aprock 
* @hawkingnetwork 
* @developmentnow
* @marcelio911
* @davidstoneham

**Comment by aprock** [comment]
So, Instead of forking it, if you'd like I can grant you access to the repository and rights to update the npm package since that is the one that is published?

-Andy

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by aprock** [comment]
meaning the one under my account.
https://github.com/aprock/react-native-tcp

I started the project at Peel, and then left and forked it so development could continue.

-Andy

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Rapsssito** [comment]
@aprock I really appreciate your fork, I've used it a lot! However, I have come across a lot of people having troubles getting help about that library because the **`issues`** are located in Peel's repository. Also, contributors are still creating PR's for that repository, ignoring that the one in **npm** is your fork. I have also found a lot of other forks born from ignored PR's in the original repository.

**I think it is worth sacrificing the name of library, in exchange for getting an active and unified repository.** Since you created the most used fork, you could create a `react-native-tcp-sockets` repository, mark the fork as moved and start getting **`issues`** and PR's there. It is very important for the library to receive active feedback, so it can evolve and adapt. (Also @phillbaker wouldn't have to be checking Peel's repository all the time looking for ignored PRs).

I have published this package in [npm](https://www.npmjs.com/package/react-native-tcp-socket), so anyone can use it in their projects.

**Comment by aprock** [comment]
Those are fair points. Best of luck!

-Andy

**Comment by phillbaker** [comment]
@aprock would you mind enabling issues on your fork? That at least addresses one of the concerns.

**Comment by Rapsssito** [comment]
That would be a great start! However, I don't think hosting the library on a fork is maintainable in the long run. @phillbaker or @aprock would you like to become maintainers of this library or maybe create a new one, marking the fork as moved?
