### ISSUE TITLE
Server on data events stop working

### ISSUE THREAD

**Issue by snapxtp** [Rapsssito/react-native-tcp-socket#10]
Hi;
socket.on('data',  (data) => { ... stops working after creating server and throwing several client requests.
Server events stop working. But the server is still running

Device Android and Android emulator (android 7 ... android 9)
"react": "16.9.0",
"react-native": "0.61.2",
"react-native-tcp-socket": "^3.0.2",

**Comment by Rapsssito** [comment]
Could you provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of this issue?

**Comment by snapxtp** [comment]
I have a small tcp data send application. With this application I send data to another application that I made using your plugin.

I'm building a release apk for Android and installing it on my device. 

When I start sending data, the server stops working after an average of 3-10 data exchanges.

Interesting but when I get an apk build with debug mode I don't encounter this problem and the application is running more stable.

**Comment by Rapsssito** [comment]
Let's look for a solution.
**First**, check if your other application is sending the data correctly.
**Second**, check if this issue also happens on iOS.
**Third**, if could you provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), it would be very useful.

**Comment by snapxtp** [comment]
"react": "16.9.0",
"react-native": "0.61.2",
"react-native-tcp-socket": "^3.0.2",

import TcpSocket from 'react-native-tcp-socket'
![image](https://user-images.githubusercontent.com/18392863/70394272-9f1eab00-1a04-11ea-8448-aa1b52a567f9.png)

**Comment by Rapsssito** [comment]
Could you provide the code causing this bug?

**Comment by snapxtp** [comment]
I just added the plugin and tried to make a simple example. i get this error for ios

const serverPort = 3000;
        let serverHost = "0.0.0.0";
        this.server = TcpSocket.createServer((socket) => {
            socket.on('data', (data) => {
     console.log('data')
            });
            socket.on('error', (error) => {
                console.log('Server error ', error)
            });

            socket.on('close', () => {
                console.log('Socket closing...')
            });
            socket.write('Data Read Done');
            socket.close();
        }).listen(serverPort, serverHost, () => {
            //this.updateChatter('opened server on ' + JSON.stringify(server.address()));
        });

        this.server.on('error', (error) => {
            console.log('An error ocurred with the server', error);
        });

        this.server.on('close', () => {
            console.log('Server closed connection');
        });

**Comment by Rapsssito** [comment]
Working on the issue.

**Comment by Rapsssito** [comment]
I've released a fix: `3.0.3`, my latest commits broke something about the eventEmitter, sorry about that.
Please, upgrade and comment what is your issue.

**Comment by snapxtp** [comment]
Yes now it works perfectly thanks
