### ISSUE TITLE
connection closed

### ISSUE THREAD

**Issue by pouyagholami** [Rapsssito/react-native-tcp-socket#107]
after run the below code , immediately encounter this error "connection error"

  const client = TcpSocket.createConnection(
      {
        port: 502,
        host: '192.168.1.190',
        reuseAddress: true,
        // timeout: 500,
      },
      address => {
        console.log('sent', data);
        client.write(data);
      },
    );
  
    client.on('data', data => {
      console.log('data recives  from modebus OK!!!', data);
    });
    client.on('error', error => {
      console.log('error Modbus TEST', error);
    });
    client.on('close', () => {
      console.log('Modbus connection closed');
    });

**Comment by Rapsssito** [comment]
@pouyagholami, I am sorry, but this does not look an error with this library rather with your setup or network.
