### ISSUE TITLE
Error: Binding socket to network 103 failed: EPERM (Operation not permitted)

### ISSUE THREAD

**Issue by ksetrin** [Rapsssito/react-native-tcp-socket#108]
## Description
Error:  `Binding socket to network 103 failed: EPERM (Operation not permitted)`

## Steps to reproduce
1. Try to connect 
```js
        socket = new net.Socket();
        socket.connect(
          {
            port: PORT,
            host: HOST,
            reuseAddress: true,
            interface: 'wifi',
          },
        );
        socket.on('error', console.log);
```

## Current behavior
I'm trying to connect to socket but I'm catching the error
It happens only when I try on device, with emulator it works fine

## Relevant information
OS: android
react-native: 0.63.4
react-native-tcp-socket: 5.2.0

**Comment by Rapsssito** [comment]
@ksetrin, what Android device are you using?

**Comment by ksetrin** [comment]
> @ksetrin, what Android device are you using?

Redmi 4
MIUI Global 9.5
Android 6.0.1 MMB29M

**Comment by Rapsssito** [comment]
@ksetrin, are you using a port under `1024`?

**Comment by ksetrin** [comment]
> @ksetrin, are you using a port under `1024`?

yes, I use 8080

**Comment by Rapsssito** [comment]
@ksetrin, check if that port is not already been used by other service.

**Comment by traviswsims** [comment]
I have the same problem, however removing the `interface: 'wifi'` option seems to to "fix" it.

**Comment by Rapsssito** [comment]
@traviswsims, it might be related to another process using port 8080 in the WiFi interface.
