### ISSUE TITLE
Import in MainAplication.java

### ISSUE THREAD

**Issue by jasenkabalac** [Rapsssito/react-native-tcp-socket#11]
What is the proper import ?

import com.asterinet.react.TcpSocketsModule;
or 
import com.peel.react.TcpSocketsModule;

Second one is made during normal instalation

**Comment by Rapsssito** [comment]
For this library, it should be `import com.asterinet.react.TcpSocketsModule`

**Comment by Rapsssito** [comment]
@jasenkabalac did you use `yarn add react-native-tcp-socket` or `npm install react-native-tcp-socket`?
