### ISSUE TITLE
Is this library compatible cross platform( ios->android and android->ios) ?

### ISSUE THREAD

**Issue by savitaraghuvanshi** [Rapsssito/react-native-tcp-socket#112]
Hi @Rapsssito ,
I am a Java developer new to mobile technologies . I have been researching the below requirement for quite a long time using react native . Please can you guide me if your library can support it or not ?

"My goal is to transfer messages between 2 mobile devices(cross platform) in offline mode " .I tried some Bluetooth react native libraries. They are ok android to android and ios to ios but they do not work cross platform .I wanted to know whether it can work cross platform ?

My specific requirement is :

1. There are 2 mobile devices that can be IOS/Android on the same location and both are both offline .
2. Device A scan the QR code from device B.
3. Device A send msg to device B Based on info on QR code
4. Device B responds to device A .....and back and forth messaging .

Appreciate your help .

**Comment by Rapsssito** [comment]
@savitaraghuvanshi, this library just provides a TCP interface from JS to the native code. Since TCP is cross-platform, this library is also cross-platform.

**Comment by savitaraghuvanshi** [comment]
Thanks for your reply .
