### ISSUE TITLE
Question: best way to find an open port?

### ISSUE THREAD

**Issue by happymaskterriblefate** [Rapsssito/react-native-tcp-socket#116]
Hi there -- thank you for your great TCP library! I was wondering if you have advice on how to find an open port for listening on the device?

I may be a bit paranoid, but I'm worried that I'm going to ship my app and then my port choice will collide with another app on a user's device. My entire app will cease to function if the local tcp doesn't start up. Is this something that I should be worried about? Is there a recommended approach to finding an open port on the device?

Thank you in advance.

**Comment by Rapsssito** [comment]
@happymaskterriblefate, you should always use ports above 1024. However, before using those ports above 1024 it is highly recommended to inform yourself about that port, I simple Google search should be enough.
