### ISSUE TITLE
ascii data not being sent via write method

### ISSUE THREAD

**Issue by Antakarana** [Rapsssito/react-native-tcp-socket#118]
## Description
ascii data not being sent via write method.

## My code:
        const client = TcpSocket.createConnection(options, () => {
            client.write([56, 48, 48, 53, 48, 53], 'ascii', (error) => console.log('error', error));

            client.destroy();
        });
        client.on('data', function (data) {
            console.log('message was received', JSON.stringify(data));
        });
        client.on('error', function (error) {
            console.log(error);
        });
        client.on('close', function () {
            console.log('Connection closed!');
        });

## Current behavior
error on console.log is coming null
and then Connection closed!

## Expected behavior
ascii data must be sent and then message was received and received data logs must be come.

**Screenshot**
<img width="1377" alt="Screen Shot 2021-08-06 at 11 45 43" src="https://user-images.githubusercontent.com/29573345/128484059-4e2d2b2f-65f3-4a74-82f1-c1925fcf16b7.png">

## Relevant information
OS: android
react-native: 0.64.2
react-native-tcp-socket: ^5.2.1

**Comment by Rapsssito** [comment]
@Antakarana, I am sorry for your issue. Have you tested your code using [Node's net API](https://nodejs.org/api/net.html)?

**Comment by Antakarana** [comment]
I am sorry too, there is no any error about this. The ascii data should have been sent with \n for our server.
Thank you.
