### ISSUE TITLE
Comunication between devices

### ISSUE THREAD

**Issue by cristianpedroso** [Rapsssito/react-native-tcp-socket#12]
Hi, i'm trying to connect from another device to the server using the wifi direct IP, but when i try to connect the output is: 

> client error failed to connect to /192.168.49.1 (port 8007) from /120.0.0.1 (port  36497): connect  failed: EINVAL (Invalid argument).

To get the server address ip i'm using `react-native-wifi-p2p`.

When i use the ip to connect from the same device of the server it work.

**Comment by Rapsssito** [comment]
It looks like you are trying to connect to LAN IP from an **invalid IP** (`120.0.0.1`).

**Comment by cristianpedroso** [comment]
Sorry... the problem is that i'm using the localAddress: "127.0.0.1", in client server, my bad.

Thx for the library.
