### ISSUE TITLE
Support to react-native windows

### ISSUE THREAD

**Issue by esnunes** [Rapsssito/react-native-tcp-socket#123]
Although Windows is a non-first-class citizen on react-native ecosystem, do you have plans to add support to it?

In case you don't, is there any concerns or red flags regarding adding support to it? Would you accept a PR adding support to it (considering that it follows the repository's standards)?

Thanks!

**Comment by enverbisevac** [comment]
It would be nice to support windows and mac :)

**Comment by Rapsssito** [comment]
@enverbisevac, there is already support for mac!

**Comment by enverbisevac** [comment]
I opened a ticket - [react-native-windows](https://github.com/microsoft/react-native-windows/issues/8803)
