### ISSUE TITLE
Reusable address

### ISSUE THREAD

**Issue by matheusmorett2** [Rapsssito/react-native-tcp-socket#13]
How can i set reusable address to avoid Address already in use?

**Comment by Rapsssito** [comment]
Currently, there is no possibility for reusable address. Sorry about that.

**Comment by matheusmorett2** [comment]
Maybe i can help you with this issue. How do you recreate the socket connection?

**Comment by Rapsssito** [comment]
@matheusmorett2 feel free to open a PR with the feature! Look at the Obj-C and Java code for more information about the socket creation.

https://github.com/Rapsssito/react-native-tcp-socket/blob/de2124a6e5cd9f8f1e350295f0008ea2098bcb2a/android/src/main/java/com/asterinet/react/tcpsocket/TcpSocketClient.java#L32-L48

https://github.com/Rapsssito/react-native-tcp-socket/blob/de2124a6e5cd9f8f1e350295f0008ea2098bcb2a/ios/TcpSocketClient.m#L55-L89

**Comment by Rapsssito** [comment]
@matheusmorett2, I have created a PR (#17) for this feature. Feel free to contribute there!
