### ISSUE TITLE
When TLS True than error coming - kCFStreamErrorDomainSSL error -9807

### ISSUE THREAD

**Issue by piyush2cloud** [Rapsssito/react-native-tcp-socket#138]
When trying to make a tls connnection from IOS to Android TV than below error comes.

`**operation couldn’t be completed. (kcfstreamerrordomainssl error -9807.)**`

I am sending tls:true in createConnection

const client = TcpSocket.createConnection({
    port: 6467,
    host: "Android TV I.P",
    tls: true
});

When tls is false it makes connection but i want to make a tls connection. Please help me in this. I have given all my head around it but not able to find any solution.

@Rapsssito Can u please help here

**Comment by Rapsssito** [comment]
@piyush2cloud, may your issue be related to #138?
