### ISSUE TITLE
Android CertPathValidatorException when sending TLS True

### ISSUE THREAD

**Issue by techie-gabbar** [Rapsssito/react-native-tcp-socket#139]
```
 var options = {
              port: 6467,
              host: host,
              tls: true,
              tlsCheckValidity: false,
              tlsCert: require('./public-cert.pem')
         }

            const client = TcpSocket.createConnection(options, () => {
              console.log("Connccted");
            });
```

When sending above thing in Android. Than Below Error is coming. Can u please help. The public-cert.pem is in my root react native project.

ERROR:
"**java.security.cert.CertPathValidatorException**: Trust anchor for certification path not found."

@Rapsssito @joshuamiller @eddieAnthem Please Help

**Comment by Rapsssito** [comment]
@techie-gabbar, make sure you follow the docs and [add the file to the metro.config.js file](https://github.com/Rapsssito/react-native-tcp-socket#self-signed-ssl-only-available-for-react-native--060).

**Comment by techie-gabbar** [comment]
@Rapsssito I followed the docs and this below is mine metro.config.js file

```
const { getDefaultConfig } = require('metro-config');
const defaultConfig = getDefaultConfig.getDefaultValues(__dirname);

module.exports = {
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: true,
      },
    }),
  },
  resolver: {
    assetExts: [...defaultConfig.resolver.assetExts, 'pem'],
  }
};
```
@Rapsssito Is there anything wrong i am doing. Can u help m what i am doing wrong.

```
  var options = {
              port: 6467,
              host: host,
              tls: true,
              // tlsCheckValidity: false,
              // tlsCert: require('./client.pem'),
              //tlsCert: require('./public-cert.pem')
}
```

**Comment by techie-gabbar** [comment]
> @Rapsssito I followed the docs and this below is mine metro.config.js file
> 
> ```
> const { getDefaultConfig } = require('metro-config');
> const defaultConfig = getDefaultConfig.getDefaultValues(__dirname);
> 
> module.exports = {
>   transformer: {
>     getTransformOptions: async () => ({
>       transform: {
>         experimentalImportSupport: false,
>         inlineRequires: true,
>       },
>     }),
>   },
>   resolver: {
>     assetExts: [...defaultConfig.resolver.assetExts, 'pem'],
>   }
> };
> ```
> 
> @Rapsssito Is there anything wrong i am doing. Can u help m what i am doing wrong.
> 
> ```
>   var options = {
>               port: 6467,
>               host: host,
>               tls: true,
>               // tlsCheckValidity: false,
>               // tlsCert: require('./client.pem'),
>               //tlsCert: require('./public-cert.pem')
> }
> ```

@Rapsssito Can u please help in above. It would be great help.

**Comment by Rapsssito** [comment]
@techie-gabbar could you post the full error stack trace?
