### ISSUE TITLE
Help needed- Implementing react-native-tcp-socket in device , how to client in browser?

### ISSUE THREAD

**Issue by im-aayan** [Rapsssito/react-native-tcp-socket#142]
I have built a socket connection (server) in the react-native app using react-native-tcp-socket, so I want to establish the connection with the server using the client in the browser which library I should use in the browser as a client?

**Comment by Rapsssito** [comment]
@handsome-me, for questions like this, you can search in sites like stackoverflow for similar questions using NodeJS net API. This library mimics almost completely NodeJS API.
