### ISSUE TITLE
Attempt to invoke virtual method 'java.io.OutputStream' java.net.Socket.getOutputStream on a null object reference.

### ISSUE THREAD

**Issue by sergeu90** [Rapsssito/react-native-tcp-socket#146]
## Description
When I click for the first time everything is fine. Sometimes I click a second time and it's also good, but there is such a random error
## Steps to reproduce

```
const client = TcpSocket.createConnection({
            host: printer.ip,
            port: printer.port,
          }, () => {
            client.write(data);
            client.destroy();
          });

          client.on('error', (error) => {
          });

          client.on('close', () => {
          });
  });
```

## Current behavior
I have print btn.
Attempt to invoke virtual method 'java.io.OutputStream' java.net.Socket.getOutputStream on a null object reference.

## Expected behavior
Code to need works.

**Screenshots**

![2022-03-27 22 51 54](https://user-images.githubusercontent.com/7217517/160298280-6201462f-7375-4cb0-ae47-7aa7f3017db8.jpg)

## Relevant information
|             |     |
| ----------- | --- |
| OS | android   |
| react-native | 0.64.3   |
| react-native-tcp-socket  | 5.6.0 |

**Comment by Rapsssito** [comment]
@sergeu90, you must take into account that `socket.write()` is asynchronous, so, in your code, `socket.destroy()` might be called first. This will destroy the socket and then try to write to it. That's why you get that error.

A workaround would be to use the callback provided by `socket.write()` to make sure you destroy the socket after writing.

**Comment by sergeu90** [comment]
@Rapsssito  Thanks a lot for helping. It is working.

```
 client.write(data, null, () => {
              client.destroy();
            });
```

**Comment by Rapsssito** [comment]
Glad it worked! I will close the issue now.
