### ISSUE TITLE
WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.

### ISSUE THREAD

**Issue by andrewhavens** [Rapsssito/react-native-tcp-socket#150]
## Description
Using react-native-tcp-socket v5.6.1 and seeing this warning:

```
 WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.
 WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method.
```

## Steps to reproduce
I tracked it down to importing this library:

```
import TcpSocket from 'react-native-tcp-socket'
```

Looks like it's coming from this line: https://github.com/Rapsssito/react-native-tcp-socket/blob/master/src/Globals.js#L10

## Expected behavior
I'm not sure what the solution is, but the warning should be addressed so that it doesn't cause the warning anymore.

## Relevant information
|             |     |
| ----------- | --- |
| OS | macOS 12.3.1   |
| react-native | 0.68.1   |
| react-native-tcp-socket  | 5.6.1  |

**Comment by Rapsssito** [comment]
@andrewhavens I believe the latest version fixes it!

**Comment by andrewhavens** [comment]
Thank you @Rapsssito!
