### ISSUE TITLE
是不支持局域网socket连接吗？

### ISSUE THREAD

**Issue by yeship** [Rapsssito/react-native-tcp-socket#152]
本机ip地址：192.168.2.62
socket服务ip地址：192.168.2.31

会报Cannot assign requested address的错误。

**Comment by Rapsssito** [comment]
@yeship, I am sorry but I don't understand your language. Could you please ask it in English?

**Comment by yeship** [comment]
@Rapsssito I get an error;
my client ip address is : 192.168.2.62
but server ip address is : 192.168.2.31
i will get the error: Cannot assign requested address
Does not support LAN connection?

**Comment by Rapsssito** [comment]
It does, but make sure you are trying to set the address for the WiFi interface rather than the cellular interface.
