### ISSUE TITLE
java.lang.IllegalArgumentException Tcp Sockets: No socket with id

### ISSUE THREAD

**Issue by pajkho** [Rapsssito/react-native-tcp-socket#167]
## Description
Sometimes when the connection gets interrupted while writing data the app will crash with "No socket with id" error. I suspect that this might be due to the write method not catching the errors that is thrown by getTcpClient method. 

## Steps to reproduce
1. Write on the socket while it simultaneously gets disconnected. 

## Current behavior
App crashes with error 

## Expected behavior
Connection can close but app should not crash. 

## Relevant information
|             |     |
| ----------- | --- |
| OS | no  |
| react-native | yes |
| react-native-tcp-socket  | yes   |

**Comment by Rapsssito** [comment]
@pajkho, this is a common issue if you are trying to use the socket while it has not established a connection yet. Make sure you wait for the connection callback before using the socket.

**Comment by pajkho** [comment]
The issue arises for us when having continuous writes to the tcp connection which doesn't stop until the end event happens. If the connection closes there can be a gap between the close of the connection and the end event where there is new writes which causes this error and the app crashes.

Wouldn't it be more reasonable to try/catch this to prevent the app from crashing and instead call the error event? It shouldn't be possible to crash the app because you mistakenly try to write to a closed connection.

**Comment by Rapsssito** [comment]
@pajkho, indeed, I will release a fix ASAP.

**Comment by yang-Ann** [comment]
Hello, this fix is missing in version 6.1.0 `socketMap.remove(cId);`

[https://github.com/Rapsssito/react-native-tcp-socket/blob/418351231efea642385e7bc01ff30eb53e0a6e67/android/src/main/java/com/asterinet/react/tcpsocket/TcpSocketModule.java#L137](link)

**Comment by Rapsssito** [comment]
Woops. My bad. I will fix it ASAP.

**Comment by Rapsssito** [comment]
@yang-Ann, this fix is included in the latest version. The solution was to remove `socketMap.remove(cId);`.

**Comment by yang-Ann** [comment]
Thank you very much




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Rodrigo ***@***.***&gt;; 
发送时间: 2024年7月9日(星期二) 下午5:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Rapsssito/react-native-tcp-socket] java.lang.IllegalArgumentException Tcp Sockets: No socket with id (Issue #167)














 
@yang-Ann, this fix is included in the latest version. The solution was to remove socketMap.remove(cId);.
