### ISSUE TITLE
tls authentication support ?

### ISSUE THREAD

**Issue by punjasin** [Rapsssito/react-native-tcp-socket#174]
i have a tcp socket tls with self sign certificate and also client private key for authentication

how do I perform authenticating using this library

**Comment by Rapsssito** [comment]
@punjasin, please, take a look at the [documentation](https://github.com/Rapsssito/react-native-tcp-socket#self-signed-ssl-only-available-for-react-native--060).

**Comment by punjasin** [comment]
@Rapsssito but it only has CA which only verify server is sign with certificate but not authenticate using client private key and client cert for authorized client
