### ISSUE TITLE
How to set up cross domain on the server

### ISSUE THREAD

**Issue by linhuanfengQ** [Rapsssito/react-native-tcp-socket#179]
## Steps to reproduce

Or code:
```js
// Your code
```

## Current behavior
A clear and concise description of what happened.

## Expected behavior

**Screenshots**

## Relevant information
|             |     |
| ----------- | --- |
| OS | ?   |
| react-native | ?   |
| react-native-tcp-socket  | ?   |

**Comment by Rapsssito** [comment]
There is no question description...
