### ISSUE TITLE
TypeError: Cannot read property 'connect' of null, js engine: hermes

### ISSUE THREAD

**Issue by XiaoSGentle** [Rapsssito/react-native-tcp-socket#182]
## Description
TypeError: Cannot read property 'connect' of null, js engine: hermes

Or code:
```js
  const Connect = () => {
    const socket = TcpSocket.default.createConnection(
      { host: "127.0.0.1", port: 6215 },
      () => {}
    );
  };

```
I used a Button event to call
![bb6bd29a0515cbde08fda4254dddeee](https://github.com/Rapsssito/react-native-tcp-socket/assets/107936135/af05f8cd-c91f-4ffb-b5ef-7ff2e9ada0eb)

## Relevant information
|             |     |
| ----------- | --- |
| OS | Android  |
| react-native | 0.72.6  |
| react-native-tcp-socket  | 6.0.6   |

**Comment by XiaoSGentle** [comment]
I hope to get an answer. Thank you very much.

**Comment by XiaoSGentle** [comment]
I'm using React-Native without error, I was using expo, it's great!

**Comment by pkaminski2108** [comment]
How did you fix it? @XiaoSGentle

**Comment by XiaoSGentle** [comment]
> How did you fix it? @XiaoSGentle

Expo doesn't support the use of TCP, downgrading to a normal ReactNative project is fine

**Comment by realicedicerice** [comment]
Same here, I'm not using expo

**Comment by 418442040** [comment]
> > How did you fix it? @XiaoSGentle
> 
> Expo doesn't support the use of TCP, downgrading to a normal ReactNative project is fine

是把expo构建出原生代码吗?还是直接使用react-native的cli?我expo构建了没效果

**Comment by XiaoSGentle** [comment]
> > > How did you fix it? @XiaoSGentle
> > 
> > 
> > Expo doesn't support the use of TCP, downgrading to a normal ReactNative project is fine
> 
> 是把expo构建出原生代码吗?还是直接使用react-native的cli?我expo构建了没效果

react-native的cli ，我后来用flutter了
