### ISSUE TITLE
Impossible to unregister event listener

### ISSUE THREAD

**Issue by Mi-La** [Rapsssito/react-native-tcp-socket#21]
See implementation in `TcpSocket.js`:
```
 on(event, callback) {
        switch (event) {
            case 'data':
                this._eventEmitter.addListener('data', (evt) => {
                    if (evt.id !== this._id) return;
                    const bufferTest = Buffer.from(evt.data, 'base64');
                    callback(bufferTest);
                });
                break;
```
Note that the listener function passed to the _eventEmitter is not the given callback, but a wrapper `(evt => {...`. Therefor it is impossible to use the `off` method to unregister the callback.
```
    off(event, callback) {
        this._eventEmitter.removeListener(event, callback);
    }
```

**Comment by Rapsssito** [comment]
Thanks for pointing that out! I'll change the API so `on` returns a listener with its own `remove()` function.
