### ISSUE TITLE
Unable to resolve host "http://xx.xx.xx.xx"

### ISSUE THREAD

**Issue by Pinwheeler** [Rapsssito/react-native-tcp-socket#24]
When running, failing to get a connection to the socket I have open on my local machine. I *am* able to get other socket libraries connecting. I would like to get the project running and try to tweak the project example files to connect to my local server, but cannot figure out how to do so.

Here's the error I get when using this library

`Unable to resolve host "http://10.0.2.2": No address associated with hostname` 

my Android manifest contains the required lines

```
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.CHANGE_NETWORK_STATE" />
```

**Comment by Rapsssito** [comment]
@Pinwheeler, could you please share your socket configuration object?

**Comment by Pinwheeler** [comment]
```typescript
import TcpSocket from 'react-native-tcp-socket'

export default class SocketClient {
  static create(
    port: number,
    host: string,
    listenCallback: (line: string) => void,
  ) {
    return new SocketClient(port, host, listenCallback)
  }

  private client: any

  constructor(
    port: number,
    host: string,
    listenCallback: (line: string) => void,
  ) {
    console.log('createConnection', port, host)
    this.client = TcpSocket.createConnection({port, host})
    this.client.on('data', data => {
      console.log(`[SockectClient: listenCallback: ${data}]`)
      listenCallback(data.toString())
    })
    this.client.on('error', error => console.log(`[Socket - ERROR:: ${error}]`))
    this.client.on('close', function() {
      console.log('Connection closed!')
    })
  }

  sendLine(line: string) {
    console.log(`[SocketClient sendLine: << ${line} >>]`)
    this.client.write(`${line}\r\n`, 'utf8', error => {
      if (error !== undefined) {
        console.log('Error in sendLine: ', error)
      } else {
        console.log('sendLine successful')
      }
    })
  }
}
```

**Comment by Rapsssito** [comment]
@Pinwheeler, could you provide the exact `ports` and `hosts` given to `createConnection()` method that are causing the error.

**Comment by Pinwheeler** [comment]
here's the log result of the first line of the `constructor` method
```
createConnection 9876 http://10.0.2.2
```

So those arguments should be

```
port: 9876
host: http://10.0.2.2
```

**Comment by Rapsssito** [comment]
@Pinwheeler, I think the main issue here is that `host` is the _host the socket should connect to. IP address in IPv4 format or localhost_.

Does it work if the host is set to `10.0.2.2`?

**Comment by Pinwheeler** [comment]
Haha! So it does! Thank you for your support! This library is so helpful and I'm happy that you helped me through this issue.

**Comment by Rapsssito** [comment]
Glad it worked! **And thank you so much for your sponsorship, @Pinwheeler, I really appreciate it.**
