### ISSUE TITLE
Second socket cannot connect

### ISSUE THREAD

**Issue by deiv23** [Rapsssito/react-native-tcp-socket#25]
Hi, I have no problems establishing a connection for the first time.
But after that first connection, I want to establish a new connection on the same port and ip, and the server socket (written in python) gets stuck on accept for this second connection.

Here is my code:

```
let options = {port:4444, host:self.props.ip, reuseAddress:true, localAddress:this.ipAddress, localPort:4444};
var options2 = {port:4444, host:self.props.ip, reuseAddress:true, localAddress:this.ipAddress, localPort:4444};
		
var client = TcpSocket.createConnection(options);
client.on('error', function(error) {
     console.log("error1->" + error);
});
client.write('config-' + this.ipAddress); // I receive this on the server side succesfully
client.destroy();

var client2= TcpSocket.createConnection(options2);  //this call does not trigger the accept on the server side
```

**Comment by Rapsssito** [comment]
Could you please test the code with a different server in order to determine if it is a client or server-side issue?

**Comment by deiv23** [comment]
I use same server with another app in react (not react-native), where I use 'net-socket' and it's working properly.
Previously the server was on a windows machine, now I ported it to linux, I'll keep investigating to know if it is a server-side issue.

**Comment by Rapsssito** [comment]
@deiv23, looking at your code, it looks like you are **creating both sockets on the same `localAddress` and `localPort`**, that may be causing the second client to not bind correctly.

Please, try to change the second `localPort` to a different one.

**Comment by deiv23** [comment]
Hi @Rapsssito , you were right, the problem was on the server. Now is working properly. Thanks!!

**Comment by Rapsssito** [comment]
Glad you fixed it!
