### ISSUE TITLE
Unknown interface for IP Address not 127.0.0.1

### ISSUE THREAD

**Issue by Pinwheeler** [Rapsssito/react-native-tcp-socket#26]
## Description
as in #6 but the discussion around that suggests that it's only for localhost

## Steps to reproduce
1. Using iPhone simulator
2. Connect to an IP address 
```
import TcpSocket from 'react-native-tcp-socket'
this.client = TcpSocket.createConnection({port, host})
```

## Current behavior
The socket fails to connect with error
`Unknown interface. Specify valid interface by name (e.g. "en1") or IP address.`

## Expected behavior
The socket should connect

## Relevant information
|             |     |
| ----------- | --- |
| OS | iOS   |
| react-native | 0.61.5   |
| react-native-tcp-socket  | ^3.2.3   |

**Comment by Rapsssito** [comment]
@Pinwheeler, could you provide the `host` and `port` you are using to create the connection, please?

**Comment by Pinwheeler** [comment]
Here's my logging info around it.

```
 LOG  <Socket port: 9876 host: 167.99.166.69>
 LOG  [Socket - ERROR:: Unknown interface. Specify valid interface by name (e.g. "en1") or IP address.]
```

Ah... is this because that IP address is IPv6? Dang- do you know how to convert them?

**Comment by Rapsssito** [comment]
**`167.99.166.69` is an IPv4 address**. There should not be an issue with that.

> Ah... is this because that IP address is IPv6? Dang- do you know how to convert them?

You can't convert all IPv6 addresses to IPv4 - there are more IPv6 addresses than there are IPv4 addresses.

**Comment by Rapsssito** [comment]
@Pinwheeler, it is indeed a bug with the `localAddress` handling on the iOS part when connecting. Thanks for the feedback! I will update when a fix is ready.

**Comment by Rapsssito** [comment]
@Pinwheeler, I have released a **fix version ([3.2.7](https://github.com/Rapsssito/react-native-tcp-socket/releases/tag/v3.2.7))**. Could you please test if the issue persists using that version?

**Comment by Pinwheeler** [comment]
Checked using the latest version and the issue is resolved. Thanks again!

**Comment by Rapsssito** [comment]
Glad it worked!
