### ISSUE TITLE
null is not an object: evaluating 'Sockets.connect'

### ISSUE THREAD

**Issue by nthungmta207** [Rapsssito/react-native-tcp-socket#27]
Help!
My project cant import TcpSocket from 'react-native-tcp-socket' and it show:
TypeError: null is not an object ( evaluating 'Sockets.connect')

**Comment by Rapsssito** [comment]
@nthungmta207, could you provide more info about your problem (code, OS, module version)?

**Comment by nthungmta207** [comment]
![image](https://user-images.githubusercontent.com/31845106/74827892-bcdf8900-5340-11ea-8baf-1eaf8c111716.png)

**Comment by nthungmta207** [comment]
![image](https://user-images.githubusercontent.com/31845106/74828030-f7492600-5340-11ea-8b2e-e4a63b4d1279.png)

**Comment by nthungmta207** [comment]
thanks

**Comment by Rapsssito** [comment]
@nthungmta207, please, do not share code in photo format, it could compromise your privacy and it is difficult to understand/read.

Taking a look at your initial post, I think the issue is that you are calling `Sockets.connect` while you are importing `'react-native-tcp-socket'` as `TcpSocket`. **The correct way to call it is `TcpSocket.connect`**.

**Comment by nthungmta207** [comment]
import React, { Component } from 'react';
import { 
  View,
  Text, 
  StyleSheet, 
  Dimensions, 
  TextInput, 
  KeyboardAvoidingView,
  textInputOpacity,
  Alert,
} from 'react-native';
import TcpSocket from 'react-native-tcp-socket';

import Svg, {Image, Circle, ClipPath} from 'react-native-svg';
import Animated, { Easing } from 'react-native-reanimated';
import { TapGestureHandler, State, TouchableOpacity } from 'react-native-gesture-handler';

function connectServer(){
  var client = TcpSocket.createConnection({
    port: 5555,
    host: '192.168.0.108',
    localAddress: "127.0.0.1",
    reuseAddress: true,
    // localPort: 20000,
    // interface: "wifi"
}, (address) => {
    this.updateChatter('opened client on ' + JSON.stringify(address));
    client.write('Hello, server! Love, Client.');
});

class login extends Component {
  constructor() {
    super();
  }
  componentDidMount() {
    connectServer();
  }
 render() {
    <Text>Login</Text>
 }
}
export default login;

**Comment by Rapsssito** [comment]
> 
> 
> ```js
> import React, { Component } from 'react';
> import { 
>   View,
>   Text, 
>   StyleSheet, 
>   Dimensions, 
>   TextInput, 
>   KeyboardAvoidingView,
>   textInputOpacity,
>   Alert,
> } from 'react-native';
> import TcpSocket from 'react-native-tcp-socket';
> 
> import Svg, {Image, Circle, ClipPath} from 'react-native-svg';
> import Animated, { Easing } from 'react-native-reanimated';
> import { TapGestureHandler, State, TouchableOpacity } from 'react-native-gesture-handler';
> 
> function connectServer(){
>   var client = TcpSocket.createConnection({
>     port: 5555,
>     host: '192.168.0.108',
>     localAddress: "127.0.0.1",
>     reuseAddress: true,
>     // localPort: 20000,
>     // interface: "wifi"
> }, (address) => {
>     this.updateChatter('opened client on ' + JSON.stringify(address));
>     client.write('Hello, server! Love, Client.');
> });
> 
> class login extends Component {
>   constructor() {
>     super();
>   }
>   componentDidMount() {
>     connectServer();
>   }
>  render() {
>     <Text>Login</Text>
>  }
> }
> export default login;
> ```

If that is your code, you are calling `this.updateChatter('opened client on ' + JSON.stringify(address));` and `updateChatter` is undefined. Have you tried if that code throws an error?

**Comment by nthungmta207** [comment]
I have tried but it still not working

**Comment by Rapsssito** [comment]
> 
> 
> I have tried but it still not working

What error are you getting?

**Comment by nthungmta207** [comment]
![87254589_2530732397200837_8332245191419232256_n](https://user-images.githubusercontent.com/31845106/74835290-95dc8380-534f-11ea-95d7-4d19c03ba676.jpg)

**Comment by Rapsssito** [comment]
I am not able to reproduce the bug. **It might be caused by a React Native linking error**. Try to uninstall the library:
`yarn remove react-native-tcp-socket`
Install it again:
`yarn add react-native-tcp-socket`
And if you are on iOS:
`cd ios && pod install`

Finally, reinstall the app on the device.

**Comment by ivantacca** [comment]
Has anyone found a solution for this error? Thanks!

**Comment by Rapsssito** [comment]
@ivantacca, could you provide your package.json and the steps you follow to install the react-native-tcp-socket?

**Comment by manumaso** [comment]
Hi, I have the same error but in runtime, trying to connect:

> TypeError: null is not an object (evaluating 'Sockets.connect')

it's related?

I followed this example, using the 'client' code:
https://github.com/Rapsssito/react-native-tcp-socket/blob/master/examples/tcpsockets/App.js

**Comment by Rapsssito** [comment]
@manumaso, thanks for the feedback! Could you try two things?
* First try with `cd android` and run `./gradlew clean`.
* If it doesn't work try to reinstall your `node_modules`.

**Comment by ivantacca** [comment]
> @ivantacca, could you provide your **package.json** and the steps you followed to install `react-native-tcp-socket`?

Hi, I have just tried again and I'm still getting the same error

`
import * as React from 'react';
import { Text, View, StyleSheet, TouchableOpacity } from 'react-native';
import TcpSocket from 'react-native-tcp-socket';

export default class App extends React.Component {
  _connect = () => {
    client = TcpSocket.createConnection({
      host: "192.168.1.107",
      port: "80"
    });
  }

  render(){
    return(
      <View style={styles.container}>
        <TouchableOpacity
          style={styles.button}
          onPress={this._connect}
        >
          <Text>Connect</Text>
        </TouchableOpacity>
      </View>
    );
  };
}
`

`
{
  "name": "Socket_App",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-tcp-socket": "^3.5.0"
  },
  "devDependencies": {
    "@babel/core": "^7.9.0",
    "@babel/runtime": "^7.9.2",
    "@react-native-community/eslint-config": "^1.0.0",
    "babel-jest": "^25.3.0",
    "eslint": "^6.8.0",
    "jest": "^25.3.0",
    "metro-react-native-babel-preset": "^0.59.0",
    "react-test-renderer": "16.11.0"
  },
  "jest": {
    "preset": "react-native"
  }
}
`
I've used yarn add react-native-tcp-socket for the installation

**Comment by Rapsssito** [comment]
> @manumaso, thanks for the feedback! Could you try two things?
> * First try with `cd android` and run `./gradlew clean`.
> * If it doesn't work try to reinstall your `node_modules`.

@ivantacca, could you try that and reply, pls?

**Comment by ivantacca** [comment]
This worked for me! Thanks!

**Comment by ivantacca** [comment]
> @manumaso, thanks for the feedback! Could you try two things?
> 
> * First try with `cd android` and run `./gradlew clean`.
> * If it doesn't work try to reinstall your `node_modules`.

This worked for me! Thanks!

**Comment by manumaso** [comment]
> @manumaso, thanks for the feedback! Could you try two things?
> 
>     * First try with `cd android` and run `./gradlew clean`.
> 
>     * If it doesn't work try to reinstall your `node_modules`.

I tried it several times but it still doesn't work, at the moment of executing the code that involves the library it throws the same error

> TypeError: null is not an object (evaluating 'Sockets.connect')


 in line
'connect' TcpSocket.js: 152:13

Maybe it's something related with expo? I ejected expo from my project, although the application starts well, it crashes when I use the library.

**Comment by Rapsssito** [comment]
@manumaso, this problem is related to the library linking because RN is not able to find the module. It is probably caused by a cache/node_module/pods **bad synchronization** after the automatic RN linking. I don't have experience with Expo, so I don't know the exact steps you should follow.

My advise is to reset/reinstall the library, node_modules folder, metro cache, Gradle cache and pods (and probably de PC). I hope it works, reply if the issue still persists.

**Comment by manumaso** [comment]
> @manumaso, this problem is related to the library linking because RN is not able to find the module. It is probably caused by a cache/node_module/pods **bad synchronization** after the automatic RN linking. I don't have experience with Expo, so I don't know the exact steps you should follow.
> 
> My advise is to reset/reinstall the library, node_modules folder, metro cache, Gradle cache and pods (and probably de PC). I hope it works, reply if the issue still persists.

Well, thanks to it being a recently started project, what I did to fix it (after several attempts to avoid it) was to create a new project from scratch with react-native cli (since I was using Expo) and install all the dependencies again locally.

Thanks for all!

**Comment by roshan532** [comment]
> > @manumaso, thanks for the feedback! Could you try two things?
> > 
> > * First try with `cd android` and run `./gradlew clean`.
> > * If it doesn't work try to reinstall your `node_modules`.
> 
> Worked for me! Thanks!

have to try this two things please tell me
