### ISSUE TITLE
Error when writing Uint8Array to client

### ISSUE THREAD

**Issue by pouyagholami** [Rapsssito/react-native-tcp-socket#28]
## Description
I have a problem in sending byte array over TCP
```import TcpSocket from 'react-native-tcp-socket';
componentDidMount() {
    let client;
    client = TcpSocket.createConnection(
      {
        port: Number(24),
        host: '192.168.1.104',
        // localAddress: '127.0.0.1',
        // reuseAddress: true,
        // localPort: 20000,
        // interface: "wifi"
      },
      address => {
        this.updateChatter('opened client on ' + JSON.stringify(address));
        //client.write('[101]');
        var myarray = new Uint8Array([101]);
        var buf = Buffer.alloc(1, 101);
        client.write(buf);
      },
    );
```
I want to send 101 as byte over TCP but my code sends 'e' character and also sending myarray throws in the following error
](http://s7.picofile.com/file/8388794926/err.jpg)
What should I do?

| OS | Android 7  |
| react-native | 0.61.5   |
| react-native-tcp-socket  | ^3.2.6   |

**Comment by Rapsssito** [comment]
@pouyagholami, could you upgrade to the latest version of the library and check if the issue still persists?

**Comment by Rapsssito** [comment]
@pouyagholami, I have released a fix version (**[v.3.2.9](https://github.com/Rapsssito/react-native-tcp-socket/releases/tag/v3.2.9)**) with a fix for the error when sending `Uint8Array` objects.

> I want to send 101 as byte over TCP but my code sends 'e' character

Your client does not send the 'e' character, the TCP client sends a byte array ([101] in this case). However, when you call `socket.on('data', (data) => {})`, **`data` is a Buffer** object containing [101]. So, when you call its `toString()` method (directly or indirectly by concatenating it to a string), it turns the 101 byte array into the character `'e'`.

I hope this fixes your problem. Feel free to reopen this issue if you need any help!
