### ISSUE TITLE
onClose event doesn't fire when one device lose WiFi

### ISSUE THREAD

**Issue by micahbule** [Rapsssito/react-native-tcp-socket#30]
## Description
`onClose` event doesn't fire when a TCP client loses WiFi

## Steps to reproduce
1. Instantiate a TCP Server on `device1`.
2. Instantiate a TCP Client on `device2` and connect to `device1`.
3. Turn off WiFi for `device2`.

## Current behavior
Client's socket in the TCP server is still connected.

## Expected behavior
Client's socket in the TCP server must be disconnected.

## Relevant information
|             |     |
| ----------- | --- |
| OS | ubuntu 18.04  |
| react-native | 0.61.4  |
| react-native-tcp-socket  | 3.3.1  |

**Comment by Rapsssito** [comment]
@micahbule, TCP does not provide an explicit disconection event, since it is an idle protocol. You can find more information on this [article about half-open connection](https://blog.stephencleary.com/2009/05/detection-of-half-open-dropped.html).
