### ISSUE TITLE
What is the _state property?

### ISSUE THREAD

**Issue by Pinwheeler** [Rapsssito/react-native-tcp-socket#32]
taking a look at the interface for the TcpSocket object, it features a _state property integer that looks like it might tell me whether or not the socket is successfully connected. Wondering if that's allowed/what the number codes might be for determining that.

**Comment by Rapsssito** [comment]
The `_state` property is a _legacy_ private attribute (note the "_" before its name) from the class `TCPSocket`. It holds the information about the socket connection state. However, as it is a private property, **I do not recommend you to use it, as it might be removed any time soon**.

If you still want to use it, theses are the state number codes:
```javascript
const STATE = {
    DISCONNECTED: 0,
    CONNECTING: 1,
    CONNECTED: 2,
};
```

If you think that the TCPSocket interface should be enlarge with a public _state getter. Feel free to open an issue for that feature request!
