### ISSUE TITLE
The server of this API accepts external connections?

### ISSUE THREAD

**Issue by Jesus32cm** [Rapsssito/react-native-tcp-socket#33]
Hi, i'm trying to run a socket server on a react-native project (android), that's accept external connections from a client running on a desktop (nodeJS). I already make a code, but it didn't work.

So, i just want to know if this API works for external connections or i'm miss something.

Sorry for the noob question.

**Comment by Rapsssito** [comment]
@Jesus32cm, it does work with external connections. I hope your issue is resolved!

**Comment by Jesus32cm** [comment]
Yes, i already figured out what i was missing, thank you for this API
