### ISSUE TITLE
Duplicate CocoaAsyncSocket symbols with React Native 0.62.0

### ISSUE THREAD

**Issue by mfikes** [Rapsssito/react-native-tcp-socket#36]
## Description
With React Native 0.62.0, after adding `react-native-tcp-socket`, you will encounter duplicate `CocoaAsyncSocket` symbols.

## Steps to reproduce
1. `npx react-native init AwesomeProject --version 0.62.0`
2. `cd AwesomeProject`
3. `yarn add react-native-tcp-socket`
4. `cd ios`
5. `pod install`
6. `cd ..`
7. `npx react-native run-ios`
8. See error

## Current behavior
You will see duplicate symbol errors being reported looking like

```
duplicate symbol '_OBJC_IVAR_$_GCDAsyncSocket.IsOnSocketQueueOrTargetQueueKey' in:
    /Users/mfikes/Library/Developer/Xcode/DerivedData/AwesomeProject-eadydiioyrxatngliemdjgtptiol/Build/Products/Debug-iphonesimulator/CocoaAsyncSocket/libCocoaAsyncSocket.a(GCDAsyncSocket.o)
```

This may also be relevant:

```
$ find . -name GCDAsyncSocket.m
./node_modules/react-native-tcp-socket/ios/CocoaAsyncSocket/GCDAsyncSocket.m
./ios/Pods/CocoaAsyncSocket/Source/GCD/GCDAsyncSocket.m
```

## Expected behavior
No duplicate symbols should appear.

## Relevant information
|             |     |
| ----------- | --- |
| react-native | 0.62.0   |
| react-native-tcp-socket  |  3.4.0  |

## Workarounds
This appears to be a consequence of Flipper, introduced in React Native 0.62.0.

Workarounds include:
- Use React Native 0.61.5
- Remove Flipper: Comment out the lines in `ios/Podfile` that enable Flipper so that the relevant section looks like:

```
...
  use_native_modules!

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # add_flipper_pods!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
...
```

and comment out code related to Flipper in `iOS/<ProjectName>/AppDelegate.m`

**Comment by Rapsssito** [comment]
@mfikes, thanks for the feedback! Already working on a fix. I'll update you when it is released!

**Comment by Rapsssito** [comment]
@mfikes, I have released a fix. If the issue still persists, feel free to open this issue!

**Comment by phungthanhdong** [comment]
Hello,
It appears that the issue happen again in v4.0.0
![Screen Shot 2020-07-01 at 3 30 29 PM](https://user-images.githubusercontent.com/24285778/86222061-eb535780-bbaf-11ea-9568-778dc0656e2f.png)
![Screen Shot 2020-07-01 at 3 29 43 PM](https://user-images.githubusercontent.com/24285778/86222066-ec848480-bbaf-11ea-8324-de89428ba6f2.png)
Could you please update it!
Thanks

**Comment by dpankros** [comment]
I get the almost exactly the same errors as @phungthanhdong, but with two small differences (architecture and number of duplicate symbols):
```
...
duplicate symbol '_OBJC_IVAR_$_GCDAsyncSocket.connectInterface6' in:
    /Users/name/Library/Developer/Xcode/DerivedData/project-dkqveqqthdzfzfagaqunoluroubi/Build/Products/Debug-iphoneos/CocoaAsyncSocket/libCocoaAsyncSocket.a(GCDAsyncSocket.o)
    /Users/name/Library/Developer/Xcode/DerivedData/project-dkqveqqthdzfzfagaqunoluroubi/Build/Products/Debug-iphoneos/TcpSockets/libTcpSockets.a(GCDAsyncSocket.o)
duplicate symbol '_OBJC_IVAR_$_GCDAsyncSocket.connectInterface4' in:
    /Users/name/Library/Developer/Xcode/DerivedData/project-dkqveqqthdzfzfagaqunoluroubi/Build/Products/Debug-iphoneos/CocoaAsyncSocket/libCocoaAsyncSocket.a(GCDAsyncSocket.o)
    /Users/name/Library/Developer/Xcode/DerivedData/project-dkqveqqthdzfzfagaqunoluroubi/Build/Products/Debug-iphoneos/TcpSockets/libTcpSockets.a(GCDAsyncSocket.o)
ld: 79 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Underlying cause is still probably the same.

**Comment by Rapsssito** [comment]
@dpankros, could you move your comment to #61?

**Comment by angel-venchev-toptal** [comment]
@dpankros I don't think there's a version 4.1.0 what really fixed it for you?
