### ISSUE TITLE
Connection closed after first request, cannot be opened after

### ISSUE THREAD

**Issue by amcdevitt97** [Rapsssito/react-native-tcp-socket#42]
## Description
Client on react-native-tcp-socket will send and receive data on the first request, but all further requests are denied with error "connection closed". Is there any way to re-open this connection after the first one closes?

Code for client (React-native-tcp-socket needs updated): https://github.com/YCPRadioTelescope/rtMobile/blob/scripts/src/components/scriptsModal/scriptsModal.js
Code for the server is this "simple tcp server": https://sodocumentation.net/node-js/topic/6545/tcp-sockets

## Steps to reproduce
1. Run server on separate machine using 'node index.js'
2. Download project and with android emulator open, run 'react-native run-android'
3. Click on 'Run script', accept, run any of the given script options (all they do is send a string to the server over TCP)

## Current behavior
First request reaches the server fine. Any further requests result in an "Error: Socket is closed" or "Error: Attempt to invoke virtual method void java.net.socket.connect on a null object reference". Commenting out all 'client.destroy();' lines appears to fix the problem until a second or third connection is made, then no data is sent or received at all. Almost as if the request is timing out. ('selection made' indicates the button was pressed).
Client-side:
![image](https://user-images.githubusercontent.com/12824100/79374513-6009e480-7f25-11ea-9e67-c7df99536947.png)
Server-side:
![Screen Shot 2020-04-15 at 2 26 24 PM](https://user-images.githubusercontent.com/12824100/79374636-74e67800-7f25-11ea-842e-21f416bcaab9.png)

## Expected behavior
Each time the button is pressed, a request should send to the server successfully. I'm very new to networking so if I'm doing something wrong, please let me know.

**Screenshots**

Client-side:
![image](https://user-images.githubusercontent.com/12824100/79370784-45357100-7f21-11ea-9665-f20f57ae7926.png)
Server-side:
![Screen Shot 2020-04-15 at 1 59 36 PM](https://user-images.githubusercontent.com/12824100/79370859-61d1a900-7f21-11ea-8ee7-dd78eebfbfa0.png)

## Relevant information
|             |     |
| ----------- | --- |
| OS | Android v. 9 emulator   |
| react-native | 0.61.4   |
| react-native-tcp-socket  | 3.5.0  |

**Comment by Rapsssito** [comment]
@amcdevitt97 thanks for the report! I'll take a look.

**Comment by Rapsssito** [comment]
@amcdevitt97 your problem might be related to the **[line 63](https://github.com/YCPRadioTelescope/rtMobile/blob/88752df96412d397d75707f3dbeb621d97441958/src/components/scriptsModal/scriptsModal.js#L63) in the client**.
You call `client.destroy()` right after `TcpSocket.createConnection()`, which makes the client destroy itself immediately after creation. Try to **remove that line and rethink your logic**. If the issue still persists, reply back.

**Comment by amcdevitt97** [comment]
This was exactly the problem. Can't believe I missed this. Thanks for responding and catching that! Going to close the issue now.
