### ISSUE TITLE
Connect to server without IP

### ISSUE THREAD

**Issue by igor-nm** [Rapsssito/react-native-tcp-socket#44]
## Description
It's more a question that a bug.
Is it possible to connect to server by local dns os something like that? I asking for you because I'm working in a project that I won't know server IP... Actually, the server IP could be changed.

## Relevant information
| Library | Version |
| ----------- | --- |
| OS | Android & iOS |
| react-native | 0.62.2 |
| react-native-tcp-socket  | 3.5.0 |

**Comment by Rapsssito** [comment]
@igor-nm, since `react-native-tcp-socket` uses the OS native socket interface, it should work with any domain as long as your device asks the correct local DNS. If you find any issues with the library, feel free to open an issue!

**Comment by bobby-hewitt** [comment]
I’m trying to solve a similar thing. If I start a server on device X (192.168.0.1),  is there a way on device Y to connect to that server without device Y knowing the IP address of device X? Apologies if this is a stupid question.

**Comment by Rapsssito** [comment]
@bobby-hewitt you should look into discovering protocol for LAN or something like that (they are usually based on UDP). I am sorry, but it is not related to this library.
