### ISSUE TITLE
Cancel monitoring an event

### ISSUE THREAD

**Issue by haiya6** [Rapsssito/react-native-tcp-socket#5]
I want to cancel the listening event when the page exits,
Thank you.

**Comment by Rapsssito** [comment]
If you want to cancel a client, you can call it's `destroy()` method when unmounting the screen. If you want to close a server, you can do the same using it's `close()` method.

**Comment by haiya6** [comment]
```javascript
// Create socket
const client = TcpSocket.createConnection(options)
const handle = data => console.log('message was received', data)
client.on('data', handle)
// ....
// Now, I want to cancel the `handle` method that listens for data events. What should I do?
// Thank you!
```

**Comment by haiya6** [comment]
But I don't want to cancel data events that are being listened for elsewhere.

**Comment by Rapsssito** [comment]
Then, I am sorry you will need to rethink your code and logic.

**Comment by haiya6** [comment]
I think one should be provided.
  Like`EventEmitter` in Nodejs，For example:
```javascript
const ee = new EventEmitter()
ee.on('data', handle)
ee.on('data', handle2)

ee.off('data', handle2) // Cancel the `handle2` method that listens for data events.

// Then, the `handle` can continue to work.
```
Sorry, I don't know much about Android development, but I think the `NativeEventEmitter` you use has similar features, Thank you for providing `react-native-tcp-socket`~

**Comment by Rapsssito** [comment]
I'll take it a look, but as this is a rare use case, I cannot assure you that this feature will be added soon.

**Comment by Rapsssito** [comment]
Check if the last version works for you!

**Comment by haiya6** [comment]
Sorry, I didn't see the message until now, your update has been very helpful to me, thank you!
