### ISSUE TITLE
while creating server i am getting error 'An error ocuured with the server port'

### ISSUE THREAD

**Issue by Badal1234** [Rapsssito/react-native-tcp-socket#57]
## Current behavior
A clear and concise description of what happened.

## Expected behavior

**Screenshots**

## Relevant information
|             |     |
| ----------- | --- |
| OS | ?   |
| react-native | ?   |
| react-native-tcp-socket  | ?   |

**Comment by Rapsssito** [comment]
@Badal1234, could you please fill the bug report template?
