### ISSUE TITLE
How to handle file stream to byte stream?

### ISSUE THREAD

**Issue by houzhanshan** [Rapsssito/react-native-tcp-socket#60]
Sorry to disturb you again, I need to transfer files using TCP, how do I handle the file stream to byte stream

**Comment by Rapsssito** [comment]
@houzhanshan, a "file stream" is actually a byte stream. Just make sure to keep all data on a buffer and then dump it wherever you want:

```javascript
const buffer = new Buffer(0);
socket.on('data', (chunk) => {
    buffer = Buffer.concat([buffer, chunk]);
});

socket.on('close', () => {
  // Do something with the buffer
});
```

_You can find more info on this [gist](https://gist.github.com/jcarroyo/03f349d2e201fe0c988fd8e5f8c72405)_

**Comment by houzhanshan** [comment]
Thanks a lot, help me
