### ISSUE TITLE
(Happen again in v4.0.0)Duplicate CocoaAsyncSocket symbols with React Native 0.62.0

### ISSUE THREAD

**Issue by phungthanhdong** [Rapsssito/react-native-tcp-socket#61]
Hello,
It appears that the issue happen again in v4.0.0
![Screen Shot 2020-07-01 at 3 30 29 PM](https://user-images.githubusercontent.com/24285778/86222061-eb535780-bbaf-11ea-9568-778dc0656e2f.png)
![Screen Shot 2020-07-01 at 3 29 43 PM](https://user-images.githubusercontent.com/24285778/86222066-ec848480-bbaf-11ea-8324-de89428ba6f2.png)
Could you please update it!
Thanks

_Originally posted by @phungthanhdong in https://github.com/Rapsssito/react-native-tcp-socket/issues/36#issuecomment-652276415_

**Comment by Rapsssito** [comment]
@phungthanhdong, could you try refreshing your node modules folder?

**Comment by Rapsssito** [comment]
@phungthanhdong and @dpankros, make sure to refresh your pods and node_modules.

**Comment by Jiope** [comment]
Hi guys,

First of all thanks for your package @Rapsssito it's been really helpful.

@phungthanhdong, the issue also happened to me, i found a consistent way to get rid of the error.

Procedure:
1) Go to xcode
2) into project navigator, click on Pods folder
3) then select TcpSockets in targets
4) Go to Build Phases > Compile sources
5) Here remove reference to CocoaAsyncSocket

I think the issue is that both our project and TcpSocket libs imports CocoaAsyncSocket (checkout targets in step 2).

**Comment by fnando** [comment]
@Jiope thanks for the temporary (!) fix. I noticed that this is not persisted between different `pod install` executions. Is there a way of doing it or the only solution would be forking the repo and removing that item from the compile source list?

**Comment by nphau** [comment]
> Hi guys,
> 
> First of all thanks for your package @Rapsssito it's been really helpful.
> 
> @phungthanhdong, the issue also happened to me, i found a consistent way to get rid of the error.
> 
> Procedure:
> 
> 1. Go to xcode
> 2. into project navigator, click on Pods folder
> 3. then select TcpSockets in targets
> 4. Go to Build Phases > Compile sources
> 5. Here remove reference to CocoaAsyncSocket
> 
> I think the issue is that both our project and TcpSocket libs imports CocoaAsyncSocket (checkout targets in step 2).

Totally agree with you. I have a command line will be remove after Pod install:

`rm -rf Pods/Target Support Files/TcpSockets/CocoaAsyncSocket`

**Comment by akinncar** [comment]
> Hi guys,
> 
> First of all thanks for your package @Rapsssito it's been really helpful.
> 
> @phungthanhdong, the issue also happened to me, i found a consistent way to get rid of the error.
> 
> Procedure:
> 
> 1. Go to xcode
> 2. into project navigator, click on Pods folder
> 3. then select TcpSockets in targets
> 4. Go to Build Phases > Compile sources
> 5. Here remove reference to CocoaAsyncSocket
> 
> I think the issue is that both our project and TcpSocket libs imports CocoaAsyncSocket (checkout targets in step 2).

This solution did the trick for me but,
Is it possible to solve this problem in the library instead use this temporary fix? 
I can try to help if you guys have any idea how to solve it.

**Comment by Azaz0723** [comment]
> I am facing same issue and in compile resources there was not CocoaAsyncSocket there was GCDAsyncUdpSocket.o i have removed it accordingly after that building project the duplicate architecture number goes from 144 to 65 duplicate symbols for architecture x86_64 and build fails at this. kindly help

**Comment by mohit792** [comment]
Hi everyone , i solved this issue finally with reproduce .
SOLVED !!!
1. uninstall the react-native-udp 
2. install the latest version
