### ISSUE TITLE
no client found with id X

### ISSUE THREAD

**Issue by deiv23** [Rapsssito/react-native-tcp-socket#63]
Hi, I have problems on IOS, when I try to reuse the socket I receive:
Error in connect() function
no client found with id X

Same code is running ok on Android. First connection works ok on IOS

**Comment by Rapsssito** [comment]
@deiv23, could you please fill the issue "bug template" form?

**Comment by deiv23** [comment]
**Description**

I have problems on IOS, when I try to reuse the socket I receive:
Error in connect() function
no client found with id X

**Dependencies**

react-native 0.61.5
react-native-tcp-socket 3.2.4


**Steps to reproduce the behavior:**

    create a client socket.
    define on error callback
    write to socket.

**Current behavior**

    if I execute the previous sequence once, all works ok
    second time gives the error:
         Error in connect() function
         no client found with id X

   In android works ok every time.

**Expected behavior**

   work ok on second try

**Comment by Rapsssito** [comment]
Moved to #64
