### ISSUE TITLE
iOS: No client found with id X

### ISSUE THREAD

**Issue by deiv23** [Rapsssito/react-native-tcp-socket#64]
**Description**

I have problems on IOS, when I try to reuse the socket I receive:
Error in connect() function
no client found with id X

**Dependencies**

react-native 0.61.5
react-native-tcp-socket 3.2.4

**Steps to reproduce the behavior:**

calling a function like this twice.

    function send()
    {
             var options = {port:4444, host: x.x.x.x, reuseAddress:true, localAdress: y.y.y.y, localPort:4445}

             var client = TcpSocket.createConnection(options);
             client.on('error', function(error) {
                 console.log(error)
             });
             client.on('data', function(data) {
                 client.destroy();
             });
             client.write(JSON.stringify(jsArray));
    }

**Current behavior**

if I execute the send() function once, everything works ok
second time gives the error:
     Error in connect() function
     no client found with id X

In android works ok every time.

**Expected behavior**

work ok on second try

**Comment by Rapsssito** [comment]
@deiv23, you are calling the socket before it has been created. You have to use the callback provided by `TcpSocket.createConnection()`:

```js
var options = {port:4444, host: x.x.x.x, reuseAddress:true, localAdress: y.y.y.y, localPort:4445}
// TcpSocket.createConnection is async
var client = TcpSocket.createConnection(options, () => {
    client.write(JSON.stringify(jsArray));
});
client.on('error', function(error) {
     console.log(error)
});
client.on('data', function(data) {
    client.destroy();
});
```

**Comment by deiv23** [comment]
@Rapsssito  thanks for the reply. Im trying to implement but that callback doesn't get called, I don't know why

**Comment by Rapsssito** [comment]
@deiv23, you can take a look at the [example code](https://github.com/Rapsssito/react-native-tcp-socket/tree/master/examples/tcpsockets) for a more exhaustive example.

**Comment by deiv23** [comment]
@Rapsssito I have the callback working, but second time I execute the function send, the createConnection callback isn't called. No errors shown.
The server is ready to respond, I tested with an external tool after the first send, and the server is ready.

**Comment by Rapsssito** [comment]
@deiv23, it might be related to a bad config on your server or a wrong logic on your client's code. I cannot help you without any more information.

**Comment by deiv23** [comment]
Hi, i tried with react-native-tcp and now its working fine. Thanks for your
help anyway
