### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by CrazyMan2** [Rapsssito/react-native-tcp-socket#7]
> Task :react-native-tcp-socket:compileDebugJavaWithJavac FAILED
I:\ReactProject\Project\WeixinFaceCheckIn\weixinfacecheckin\node_modules\react-native-tcp-socket\android\src\main\java\com\asterinet\react\tcpsocket\TcpSocketModule.java:107: 错误: 找不到符
号IDLE
        new GuardedAsyncTask<Void, Void>(mReactContext.getExceptionHandler()) {
                                                      ^
  符号:   方法 getExceptionHandler()
  位置: 类型为ReactApplicationContext的变量 mReactContext
I:\ReactProject\Project\WeixinFaceCheckIn\weixinfacecheckin\node_modules\react-native-tcp-socket\android\src\main\java\com\asterinet\react\tcpsocket\TcpSocketModule.java:141: 错误: 找不到符
号
        new GuardedAsyncTask<Void, Void>(mReactContext.getExceptionHandler()) {
                                                      ^
  符号:   方法 getExceptionHandler()
  位置: 类型为ReactApplicationContext的变量 mReactContext
I:\ReactProject\Project\WeixinFaceCheckIn\weixinfacecheckin\node_modules\react-native-tcp-socket\android\src\main\java\com\asterinet\react\tcpsocket\TcpSocketModule.java:166: 错误: 找不到符
号
        new GuardedAsyncTask<Void, Void>(mReactContext.getExceptionHandler()) {
                                                      ^
  符号:   方法 getExceptionHandler()
  位置: 类型为ReactApplicationContext的变量 mReactContext
I:\ReactProject\Project\WeixinFaceCheckIn\weixinfacecheckin\node_modules\react-native-tcp-socket\android\src\main\java\com\asterinet\react\tcpsocket\TcpSocketModule.java:192: 错误: 找不到符
号
        new GuardedAsyncTask<Void, Void>(mReactContext.getExceptionHandler()) {
                                                      ^
  符号:   方法 getExceptionHandler()
  位置: 类型为ReactApplicationContext的变量 mReactContext

编译不同过

**Comment by Rapsssito** [comment]
Dupe of #4, check out this comment: https://github.com/Rapsssito/react-native-tcp-socket/issues/4#issuecomment-552222712
