### ISSUE TITLE
Error during WebSocket handshake: net::ERR_INVALID_HTTP_RESPONSE

### ISSUE THREAD

**Issue by wangfpp** [Rapsssito/react-native-tcp-socket#71]
## Description
in web js Error during WebSocket handshake

## Steps to reproduce

Or code:
```js
const ws = new WebSocket('ws://172.16.1.219:9679');
	ws.onmessage = evt => {
		console.log(evt)
		
	}
	ws.onopen = e => {
		console.log(e);
		ws.send('aaaaa');
	}
	ws.onclose = e => {
		console.log(e);
	}
```

## Relevant information
|             |     |
| ----------- | --- |
| OS | Ubuntu20.04  |
| react-native | 0.63.1   |
| react-native-tcp-socket  | 4.2.0   |

**Comment by Rapsssito** [comment]
@wangfpp, this not related to `react-native-tcp-socket`. Please, post this question on StackOverflow.
