### ISSUE TITLE
Error:unHandled error.(undefined)

### ISSUE THREAD

**Issue by MLY123** [Rapsssito/react-native-tcp-socket#72]
## Steps to reproduce

Or code:
```js
// Your code
```

## Current behavior
A clear and concise description of what happened.

## Expected behavior

**Screenshots**

## Relevant information
|             |     |
| ----------- | --- |
| OS | ?   |
| react-native | ?   |
| react-native-tcp-socket  | ?   |

**Comment by Rapsssito** [comment]
@MLY123, could you please fill the issue "bug template" form?

**Comment by mi-mazouz** [comment]
Same issue, adding error event does not provide more information...
