### ISSUE TITLE
TOR support

### ISSUE THREAD

**Issue by Overtorment** [Rapsssito/react-native-tcp-socket#76]
Would be nice to be able to connect to  `.onion` hosts  through TOR network

**Comment by Rapsssito** [comment]
@Overtorment, I will take a look. I don't have much experience with TOR in the socket level, **any help is greatly appreciated**!

**Comment by Rapsssito** [comment]
@Overtorment, I look it up, but sadly it is out of the scope of this module. `react-native-tcp-socket` aims to provide the lowest level TCP socket API for Android & iOS, but TOR requires protocols that are built on top of TCP.

I could set up [CloudFlare's TOR DNS](https://blog.cloudflare.com/welcome-hidden-resolver/) for `.onion` domains, but the connection after that would be direct with the server IP (which defeats the whole purpose of TOR).
