### ISSUE TITLE
Server and client communication

### ISSUE THREAD

**Issue by snapxtp** [Rapsssito/react-native-tcp-socket#8]
Hi;
Thanks to your help I created a server and client connection.
The client sends a message to the server and the client returns a reply, after that I did not stop the server and do not destroy the client everything stops...

Sending an external request to the server. The data I send falls to the following area then my expectation is that the server sends this data to the connected clients.
server receives data but no client transaction

 socket.on('data', (data) => {
   //data arrived
    socket.write( data);
  });

client.on('data', function(data) {
 //No move
  console.log('message was received', data);
});

Platform ios ,
"react": "16.9.0",
"react-native": "0.61.4",

I hope I'm not bothering you. thank you for your attention

**Comment by Rapsssito** [comment]
Can you share your full code and document where the bug is? I think I do not understand your issue.

**Comment by snapxtp** [comment]
What i want to do. Creating a server and receiving data from this server by clients connected to the server. However, once the server and client send and receive messages, communication is interrupted.
![image](https://user-images.githubusercontent.com/18392863/69484561-94c9b200-0e45-11ea-97bc-8be438e4e0cd.png)

Is something like this possible ?

**Comment by Rapsssito** [comment]
Something like that is possible. However, you may understand that I cannot write the code for you.
If you have a code that you want me to debug, please, consider **sponsoring** so you will get benefits that will help you!

**Comment by snapxtp** [comment]
Hi; I think you misunderstood me. I don't want you to write the code for me. I just want to know if this plugin works for now. Because the server and client that I see in my tests, once communication stops communication. If this plugin is just a preliminary demo, of course we can discuss it for development. My english is bad sorry.

**Comment by Rapsssito** [comment]
Sorry, my fault. I am not native English.
**I can assure you that this plugin works**, I use it in production.
