### ISSUE TITLE
TcpScokets tried to override TcpSockets

### ISSUE THREAD

**Issue by MFedour** [Rapsssito/react-native-tcp-socket#86]
Hi ! I'm facing an issue at the installation
I've followed the installation tutorial but I've the following error on react-native run-android

![Screenshot_20201113-102313_control_ts4](https://user-images.githubusercontent.com/74404115/99056366-8286dd80-259a-11eb-8a5c-2591d48699ab.jpg)

There is no duplicate tcpSocket in MainApplication.java getPackages()

React native version are: 

react-native-cli: 2.0.1
react-native: 0.63.3

npm version:

6.14.8

Any idea where the problem might come from ?
Thanks you for your help

**Comment by Rapsssito** [comment]
@MFedour, I had never seen this error. Could you provide your `package.json`? You might have two libraries using the name `TcpSockets`.

**Comment by zhouyangCode** [comment]
@MFedour 
I have seen this error because I used "react-native-tcp" before, the solution:
1. Uninstall it npm uninstall react-native-tcp --save
2. Execute gradlew clean in your android directory
3. Restart the project
