### ISSUE TITLE
Is this compatible with Node 'tls' API?

### ISSUE THREAD

**Issue by radelcom** [Rapsssito/react-native-tcp-socket#87]
## Description
Just a question if this library is also compatible with Node TLS API

**Comment by Rapsssito** [comment]
@radelcom, sadly only `TcpSocket.createConnection()` has some functionalities from the tls API (take a look at the [createConnection() documentation](https://github.com/Rapsssito/react-native-tcp-socket#createconnection)). However, take into account that `tls` and `net` API's share most of the functionalities.
