### ISSUE TITLE
Handle  connection refused error

### ISSUE THREAD

**Issue by Fedour57** [Rapsssito/react-native-tcp-socket#89]
## Description

Hello, I'm trying to handle a` connection refused` error, if I try to connect to a server that doesn't exist, my app crash.

## Steps to reproduce

Code:
```
try
{
    var client = net.createConnection({ port: 49500, host: "255.0.0.0",timeout:1000 })
}
catch (error)
{
    console.log(error)
}
```

OR

```
 var client = net.createConnection({ port: 49500, host: "255.0.0.0",timeout:1000 })
 .then(val =>
{
    console.log("connected")
}           
).catch(error => {
    console.log(error)
})
```

## Current behavior
The app crash when the client can not connect to the server.

## Expected behavior
The try catch block should handle the error

## Relevant information
|             |     |
| ----------- | --- |
| react-native | 0.63.3   |
| react-native-tcp-socket  | 4.5.4  |

**Comment by Rapsssito** [comment]
@Fedour57, thanks for your feedback! Please, take a look at #53, it might be your problem. You could try some of the workarounds commented over there.
