### ISSUE TITLE
Duplicate CocoaAsyncSocket symbols with React Native 0.63.4

### ISSUE THREAD

**Issue by Hektar90** [Rapsssito/react-native-tcp-socket#91]
similar issue #61

<img width="303" alt="Bildschirmfoto 2020-12-17 um 10 39 38" src="https://user-images.githubusercontent.com/15243732/102470391-34ab3c80-4054-11eb-990a-899ad9fe3439.png">
<img width="1297" alt="Bildschirmfoto 2020-12-17 um 10 40 34" src="https://user-images.githubusercontent.com/15243732/102470630-88b62100-4054-11eb-8765-c17eac971695.png">

**Comment by Rapsssito** [comment]
Have you tried with the solution proposed here https://github.com/Rapsssito/react-native-tcp-socket/issues/61#issuecomment-653881488 ?

**Comment by nphau** [comment]
Here is fine
https://github.com/Rapsssito/react-native-tcp-socket/issues/61#issuecomment-653881488
