### ISSUE TITLE
Incorrect typing for socket.address()?

### ISSUE THREAD

**Issue by ericleb010** [Rapsssito/react-native-tcp-socket#93]
## Description
Typing for TcpSocket.address() seems to be different from what the library returns at runtime.

## Steps to reproduce

Or code:
```js
// Your code
```

## Current behavior
Calling `TcpSocket.address()` returns an object that resembles: `{family: 'IPv4', port: 54014, address: '192.168.200.143'}`

## Expected behavior
According to the type definitions, `TcpSocket.address()` should just be a string: `'192.168.200.143'`

**Screenshots**

## Relevant information
|             |     |
| ----------- | --- |
| OS | ?   |
| react-native | ?   |
| react-native-tcp-socket  | ?   |

**Comment by Rapsssito** [comment]
@ericleb010, you are right! Thanks for the feedback, working on a fix.
