### ISSUE TITLE
react-native-tcp-socket.podspec  missing a  ‘v’

### ISSUE THREAD

**Issue by jiangjiatao** [Rapsssito/react-native-tcp-socket#97]
![41F05D62-385E-4B42-8ADB-DFB58A24292D](https://user-images.githubusercontent.com/18566483/109180352-bee6ee00-77c5-11eb-8f62-68ed3d04def4.png)

**Comment by Rapsssito** [comment]
@jiangjiatao, you are right! I will fix it right now!
