### ISSUE TITLE
sending images

### ISSUE THREAD

**Issue by ruanblima** [Rapsssito/react-native-tcp-socket#99]
## Description
How can I send an image?
I tried to send it as base64, but the data does not arrive complete on the server, is it necessary to do some configuration to allow the sending of a larger data?

**Comment by Rapsssito** [comment]
@ruanblima, I am sorry, but if the image is too big, you might encounter problems. Check #78 for more info. In the meantime, you can create chunks out of your image and use the callback argument provided to `socket.write()` to space out the shipment.

**Comment by ruanblima** [comment]
> @ruanblima , sinto muito, mas se a imagem for muito grande, você pode encontrar problemas. Verifique o [nº 78](https://github.com/Rapsssito/react-native-tcp-socket/issues/78) para obter mais informações. Nesse ínterim, você pode criar pedaços de sua imagem e usar o argumento de retorno de chamada fornecido para `socket.write()`para espaçar a remessa.

Thank you very much for the tip, I will look at this question that you asked. Would you have another lib to indicate that I could be sending a larger image? my image is about 200kb, and I need to send it via socket.

**Comment by Rapsssito** [comment]
@ruanblima, I don't know any other library for larger images. I am working on a fix, as commented in #78 (using the `drain` event). Take a look at questions on StackOverflow about your problem using NodeJS net API, it should also work in this library.

**Comment by ruanblima** [comment]
> @ruanblima , não conheço nenhuma outra biblioteca para imagens maiores. Estou trabalhando em uma correção, comentado em [# 78](https://github.com/Rapsssito/react-native-tcp-socket/issues/78) (usando o `drain`evento). Dê uma olhada nas perguntas no StackOverflow sobre seu problema ao usar uma API de rede NodeJS, ela também deve funcionar nesta biblioteca.

Okay, thank you very much for the feedback.
